### ISSUE TITLE
Power objects spawning at mouse start

### ISSUE THREAD

**Issue by entibo** [a801-luadev/parkour#13]
Spawning an object right after dying sometimes puts it at the start of the map, instead of at the chair.

This happens when the power is activated during the delay between respawning the player and teleporting them to their last level.

Potential fix could be:
* disabling powers at either PlayerDied or PlayerRespawn
* re-enabling powers a few milliseconds after PlayerRespawn or after checking the player's position against their level

**Comment by tocuto** [comment]
Hey, thank for your report!!
I will try to fix it, but it might be impossible to fix. Transformice works in an asynchronous way so it can handle a lot of concurrent and parallel stuff at the same time. Being asynchronous means that I can't check against time unless it is a big time. If I add a cooldown after respawning to 1 second (needing to wait a second to use your object powers), and the player has, let's say 1200ms of ping (packets take 1.2 seconds to go from the player to the server, like the event of a keypress), imagine the server sends them the respawn event and the player presses a key, then the server sends the teleport packet. The keypress event will take 1.2s to arrive to the server, so the cooldown will be ok at the time lua processes the event. This event sends in the packet itself the x and y position of where it has been triggered (spawn point or close to it), spawning the object there.

If I make a check against the position, the cooldown problem is fixed but there is another one: Imagine this same player. The server sends respawn and somehow, takes a bit more to send teleport to the client. The client could move around near the spawnpoint, and pressing keys. The objects will spawn there. You could say I can make this position check range bigger, but no. What if the chair is near the spawn point?

Anyway, I will try to fix this. Thank youu!!

**Comment by entibo** [comment]
Aww i didn't realize it was so complicated. Well, it's not a very serious bug 😄 
Thank you for all the time you're putting into this module !

**Comment by tocuto** [comment]
I've been thinking about this and it is not worth it to fix.
