### ISSUE TITLE
Add a profiles system

### ISSUE THREAD

**Issue by tocuto** [a801-luadev/parkour#22]
I would love to have a profiles system, but it needs ideas on what to show first. I've been thinking about gathered powers, completed maps and community, but it still needs more.

**Comment by JakEr-HarmonyLess** [comment]
Add staff position if there is one
Rank in leaderboard (if the person's in)
Number or/of maps that got accepted

I also thought of a badge system (would will be requiring profile first)

**Comment by tocuto** [comment]
Thank you! I will probably implement those too. The profiles system is not gonna be implemented soon tho.
