### ISSUE TITLE
Change file structure

### ISSUE THREAD

**Issue by tocuto** [a801-luadev/parkour#23]
Basically, handling json in lua is not an easy task. Doing it on a ~5kb file is even worse. That's why I am receiving these warnings:
![image](https://user-images.githubusercontent.com/24902450/76705712-b1be1580-66c0-11ea-80c6-3f274852483d.png)
I must change it soon, since the rest of the code is running smoothly.

**Comment by tocuto** [comment]
I will probably split it into two different files too.

**Comment by tocuto** [comment]
It would be even better if I improved the way webhooks are sent. Probably using another format so it takes less space. Anyway, for now, the only file with problems is file id 2 (ranking, banned, suspects)

**Comment by Athesdrake** [comment]
You could rewrite the json encode/decode functions to work with coroutines so you can pause it and resume it the next loop.

**Comment by tocuto** [comment]
Webhooks are sent differently now, and about json encode and encode I dont really need them to be coroutines, mostly because I run the three steps (decode, parse, encode) in three different events (if it has reached a critical time, it will run in the next loop)

**Comment by tocuto** [comment]
I've stopped receiving these warnings since the new infrastructure. I'll close this issue.

**Comment by tocuto** [comment]
Even tho I've stopped receiving warnings, I'm working on a new storage system (https://github.com/a801-luadev/filemanager) to make the file storage way lighter (it used to take between 5-6ms to read file 1, it has a steady average of 0.9ms with the new system). Many improvements might to the leaderboard come since the heaviest file (due to all the sorting happening there).
