### ISSUE TITLE
Just a few suggestions

### ISSUE THREAD

**Issue by Blank3495** [a801-luadev/parkour#34]
Currently, team managers can hire/fire a player using `!rank <add/rem> <playername> <position>`, this means that in cases where they might want to add or remove more than 1 player, they would have to type that command several times, making it repititive and somewhat boring (in my case). 

Secondly, when a player types !staff, they aren't able to see all the players and have to scroll up because it returns lists of **every** parkour staff online. 

![image](https://user-images.githubusercontent.com/49693827/80641010-39be6b80-8a32-11ea-8e40-ef9810ba3723.png)

So here is my solution:
`!rank <position> <add> <player1>=<commu> <player2>=<commu> ...`
`!rank <position> <rem> <player1> <player2> ...`

This way, we can add multiple players at once, along with their community.  So if a player from TR server types !staff, it will only return staff members online in their community, and if there are no members online it can list staff members online in other communities (such as EN or Global). 

We will also assign XX as **Global** community to indicate their name will be shown whenever !staff is typed, as this is necessary in-case they would like to contact a member who is a Team Manager or an Admin.

**Comment by Blank3495** [comment]
Another suggestion would be that Souris accounts should be since it's easier to VPN farm using them, and all the banned accounts should not affect the gameplay of parkour, what I mean to say is that when a banned account is in the room, we all know they are not able to spawn/play the map but if everyone except the banned account has finished the round, the timer does not skip to 00:20.

**Comment by tocuto** [comment]
Souris and banned accounts problem should be fixed in the next update (needing to test it; but I'm pretty confident it will work)

Rank modification commands are not working now; I'll take a look later. Staff will be shown differently pretty soon.
