### ISSUE TITLE
Add power cooldown indicators 

### ISSUE THREAD

**Issue by Blank3495** [a801-luadev/parkour#9]
Basically when you use a power there will be a small icon on the top/bottom left/right of the screen that has a small image of the power you've currently used, and should go away once the cooldown is over. This would be a good indicator for the helpers to help more efficiently since they'll easily know when their powers are off cooldown, rather than spamming keys (like me).

**Comment by tocuto** [comment]
Basically I will need to change the cooldown system too, using timers (or eventLoop, which is more reliable). Might merge it with the despawn system.
